### ISSUE TITLE
Why not write JSON

### ISSUE THREAD

**Issue by gruberjl** [atomiqio/json-schema-builder#58]
Hello, I'm just getting started with JSON schema and I came across your project. I'm thinking about implementing JSON schema for an enterprise size API. I'm wondering why you chose to make this instead of simply writing the JSON schema in JSON.

Would you consider writing a pro/cons or detailing why you chose to create this?

**Comment by tshelburne** [comment]
@gruberjl It's *way* less verbose, so you can get a better idea of what's being described more quickly. It also lets you create nicer abstractions for your particular domain, and makes the schema itself a bit more dynamic when you're using it in code. Standard JSON schema `ref`s are great, but only until you have to track a trail of references 5 objects deep. (edited to make sense)
